
tareas = [
    {"id": "Reciclar correctamente los residuos de casa", "points": 10},
    {"id": "Apagar las luces cuando no sean necesarias", "points": 5},
    {"id": "Cerrar el grifo mientras me cepillo los dientes", "points": 5},
    {"id": "Usar una botella reutilizable en lugar de botellas de plástico", "points": 10},
    {"id": "Separar papel y cartón para reciclarlos", "points": 8},
    {"id": "Plantar un árbol o una planta autóctona", "points": 30},
    {"id": "Usar transporte público en lugar del coche", "points": 20},
    {"id": "Ir caminando a lugares cercanos", "points": 10},
    {"id": "Usar bicicleta para desplazamientos", "points": 15},
    {"id": "Reducir el consumo de carne durante un día", "points": 15},
    {"id": "Compostar restos orgánicos", "points": 25},
    {"id": "Recoger basura de un parque o playa", "points": 30},
    {"id": "Donar ropa que ya no utilizo", "points": 15},
    {"id": "Reutilizar envases antes de tirarlos", "points": 10},
    {"id": "Comprar productos con menos plástico", "points": 15},
    {"id": "Ahorrar energía usando bombillas LED", "points": 10},
    {"id": "Desconectar aparatos electrónicos que no uso", "points": 8},
    {"id": "Reducir el uso de bolsas de plástico", "points": 10},
    {"id": "Comprar productos locales y de temporada", "points": 15},
    {"id": "Ahorrar agua durante la ducha", "points": 10},
    {"id": "Crear un huerto urbano", "points": 25},
    {"id": "Participar en una limpieza ambiental comunitaria", "points": 35},
    {"id": "Construir un refugio para insectos beneficiosos", "points": 20},
    {"id": "Usar productos de limpieza ecológicos", "points": 10},
    {"id": "Reparar un objeto en vez de comprar uno nuevo", "points": 20},
    {"id": "Evitar desperdiciar comida", "points": 15},
    {"id": "Usar papel reciclado", "points": 5},
    {"id": "Compartir coche para reducir emisiones", "points": 20},
    {"id": "Instalar sistemas de ahorro de agua en casa", "points": 25},
    {"id": "Crear conciencia ambiental enseñando a otros", "points": 30},
    {"id": "Proteger zonas verdes evitando tirar basura", "points": 10},
    {"id": "Usar energía renovable cuando sea posible", "points": 35},
    {"id": "Reducir el consumo de productos desechables", "points": 15},
    {"id": "Plantar flores para ayudar a los polinizadores", "points": 20},
    {"id": "Recoger agua de lluvia para regar plantas", "points": 25}
]